#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

sudo: required

env:
  global:
  - secure: "OnWnF/vkeMTZ00oL6QxbasKCeXLCCOFYLqvDKz5s2+ona6KPbJRNHTey1T+lSW8nHgDtQppbBDWypRGjqeE445c5hRw200ezkkD8Y4/pRTvWhiAT1y14d+qPzGfAQSLXesBUQeepyB3qlP2WdloT+6tqLwrQ1GPspVWc5ARCVxSygsHt6/KhkPLwkAxTK3zmQC/flwHG2WiDEBsHBRFVgJMiTojpbS9qyPCmELJFkaQ8w1hk7Kt4mJOJihf+NoJ81ZCstmNFACQoBtauNJRMm965LncXOMP3GDYJFIoCeLn5RnCxFmMeGf0DhQIQZ+oBb7JUc8GsHCBCiy33GS1nB8FAHGCGJpjhWPnw3S/3C1ijpt6d6+KJWLXYu12YXvWlfXRsTyNBCZI/P2snjVWJrf5c0aMIbx+P0tRf77GPLe1Q/BF3V+HYbBq7vwsATwc85jBA/UzUG2qP0oI1G/htB+Ji/Ys7NcgwoQHv9u68mn3M3qlAS8Xi5x8F5tIsAqO5WuTIJKyykvLveCfrpzmAzogq27zuZhaKgJRB4MNA7Yuq2UOBCcRMC7j6ZUVBDHAmXEgUGW+Tg1qjMgGDf6HbeyT0oHc+6ZHqEFumOvwgwPITdu9It4fOG4qgEej9abQnk0qdVDgj022C2wEAVtcmPLMuSchCfWxA1KzMQhkFbG8="
  - secure: "mFhDpwH1WKhJKmUaJee23B4/N0R024JTMCIVqAV3JOl27Wai8GPFCrrFpuc1hWpLMRapZ57KJociSrnb0tUJ+CZZD4dbZhnR4szB6WTCusKCyHlPcvd/N/D3c3TC9KBMAO3Ac8YsH947RRivCmwCIWweUWfuarWftGqSgRMONXPP3gAUpN77KWAuAf6WQuY8/m677syPwEosbvB/SJZVlMalbKF9XRPIdqJfqwn8b7YIaG94l7z+CSULJ9EBHLkZ20eJ0IZ7huVAs6/vrm/mxHLrvEOKoRDbY1vygot6IQSO7YoA3Sobqb48YC0WtdCvtWrZ25thz/yU6maqB/Rf/OwgpT6SDyo+1ZoFEdWwtiAFvMzFENxmjrv8Us5DZvSYF1ndDYS1JQivzRGkZwCavsvSyKvUO8X6iAcXkWJtnoqoBvzALZmEANOye/b8s6HIa7RnnyfxJdavwvdeLCY/l7vt6mP07O11xqHTYBXLAkFFGd5rukOsG74iDCdFK3PlMiUamcb6qBZEdFnSPJP0zU65HR+J5BuJX4T4T86lmwn4UIsJlje58YYTMujt6j/tmy6J7AF7q8xOZAIQ+nOa/z2D5sIOMufKhD/TBp0Z9C8KbrOHRkPQSIxVmjonOX2cNv0y/l+BNTqHyqgFs6lLRpzUaar5ILSRGaxfk1SjNnU="

notifications:
  email: false
  webhooks:
    urls:
      # travis2slack webhook to enable DMs on openwhisk-team.slack.com to PR authors with TravisCI results
      secure: ZudPWFKvM+ndX1M6D1Opj6qYQLbexAgJuDJgs409LT9Je5pBuXPhho8G8rj5RwZpnZA3ZdRArG64tJXp0wil/w3nSt8Bx7B6ZhoO9hpJSWbWw3qDR2ffiZDrB6Cc2fMr+VfsvpEENJEvB8oeGmCqJmBzm9fXVoE9+nqKoDrEKF8ek9xfN63Etx3VnqORia1SyEvVWoP7F49DuRs9d2hswbFXGPhHZCLp8/p03IMvKVJT0YID7o6lxODi0Ck0GRVKOqnrRYwZbSe0hDQ5YJsY+AkFrTtYJVxDnTKlLKtEc9gTcj96SP1f9f8Noy37V4xxxBLokrjZYcCkGLT34Ef7wa14a1K8WUxahX5/eAf6TCHpZeK7o8j6cMzxFr/GK+XX5aHzWXgALdy11bastDfkmz3rTUaz0eB6eiQfSl0p/merVKkEJGjwUcJ4MrpdaB1v8QAHT0VO7qsffsdqTfOi0F9bCiupNnrhkE6rhwUZfEj2NdHz768ptjsQlTyNAH2y4Cgn37lKS7l7FrX9pVO77Qt6UuFUEpITyPpIsLHi5mYqH+3XealQoY/mKQYD3YSK3ON3sDdkU8UNMJl634mBalrb0mQQbxkRZOYSvK1Jns0hy34yW5R36SBmZ0puh0ZcHWDK9709jrhsJjns8NybKLV6N4KIoxJXcHhcDT+a7Zg=

jobs:
  include:
    - stage: package
      script: ./tools/travis/package_project.sh $SVN_USERNAME $SVN_PASSWORD

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
      openssl aes-256-cbc -K $encrypted_869d5d1753d0_key -iv $encrypted_869d5d1753d0_iv -in tools/key_sec.gpg.enc -out tools/key_sec.gpg -d;
    fi

after_failure:
  - echo "failed build"
  - ./tools/travis/cleanup.sh

after_success:
  - ./tools/travis/cleanup.sh
